### PR TITLE
find-replace-stream example

### PR DESCRIPTION
**Pull request by gabrioakamai**
Example adds ability to search & replace across a response body stream.

### CODE REVIEW

**Review by sscian — CHANGES_REQUESTED** [review]
Is it possible to add validation that the response from the url is text/html and can be searched?

**Comment by gabrioakamai** [comment]
@sscian I've been looking into this - I have a method that effectively prevents the parsing logic from executing when the content-type header isn't within what we'd like to allow ('text/html', 'javascript',  'application/json' in my initial approach), however, I noticed that for an image that exceeds 2MB, the responseProvider will truncate the unparsed body to those 2MB, since the body isn't parsed as a stream. Haven't found a way around this so I'm wondering if you have any ideas? Right now I think the best way to limit is via metadata in the PM configuration.

**Comment by gabrioakamai** [comment]
As discussed, pushed the latest commit which updates the Readme (and also another small update for the main.js)

**Review by sscian — APPROVED** [review]
Looks good to me...

**Pull request merged**
